parameters:
  name: 'Conda build job'
  vmImage: 'Ubuntu-18.04'
  py_maj: '3'
  py_min: '6'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 360
  
  pool:
    vmImage: ${{ parameters.vmImage }}
    
  steps: 
  - ${{ if or(contains(parameters.vmImage, 'macOS'),contains(parameters.vmImage, 'Ubuntu')) }}:
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: 'Add conda to PATH'
  - ${{ if contains(parameters.vmImage, 'win') }}:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: 'Add conda to PATH'

  - bash: |
        conda config --set always_yes yes --set changeps1 no && \
        conda create --yes --name pythonoccgen python=${{ parameters.py_maj }}.${{ parameters.py_min }} && \
        conda info -a && \
        source activate pythonoccgen && \
        conda install -c conda-forge occt=7.8.1 pip && \
        pip install -r requirements.txt && \
        conda list
    displayName: 'Install dependencies from conda-forge'

  - bash: |
        mkdir -p pythonocc-core/src/SWIG_files/wrapper && \
        mkdir -p pythonocc-core/src/SWIG_files/headers && \
        mkdir -p pythonocc-core/src/SWIG_files/common
    displayName: 'Create the pythonocc-core file structure'

  - bash: |
        pwd && \
        cd src && \
        source activate pythonoccgen && \
        python generate_wrapper.py
    displayName: 'Run pythonocc-generator'

  - bash: |
        wget https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V7_8_1.tar.gz && \
        tar -zxvf V7_8_1.tar.gz && \
        cd src && \
        source activate pythonoccgen && \
        ./export_occt_structure_to_json.py --output occt_toolkits.json ../OCCT-7_8_1
    displayName: 'Run occt structure exporter'
