##Copyright 2008-2019 Thomas Paviot (tpaviot@gmail.com)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# OpenCASCADE Toolkits: each ToolKit is a list of modules
#
TOOLKIT_Foundation = {'TKernel': ['FSD', 'MMgt', 'Message', 'NCollection', 'OSD', 'Plugin',
                                  'Quantity', 'Resource', 'Standard', 'StdFail', 'Storage',
                                  'TColStd', 'TCollection', 'TShort', 'Units', 'UnitsAPI'],
                      'TKMath': ['BSplCLib', 'BSplSLib', 'BVH', 'Bnd', 'CSLib', 'Convert',
                                 'ElCLib', 'ElSLib', 'Expr', 'ExprIntrp', 'GeomAbs', 'PLib',
                                 'Poly', 'Precision', 'TColgp', 'TopLoc', 'gp', 'math']}
TOOLKIT_Modeling = {'TKBRep': ['BRep', 'BRepAdaptor', 'BRepLProp', 'BRepTools', 'BinTools',
                               'TopExp', 'TopTools', 'TopoDS'],
                    'TKG2d': ['Adaptor2d', 'Geom2d', 'Geom2dAdaptor', 'Geom2dEvaluator',
                              'Geom2dLProp', 'LProp', 'TColGeom2d'],
                    'TKG3d': ['Adaptor3d', 'AdvApprox', 'GProp', 'Geom', 'GeomAdaptor', 'GeomEvaluator',
                              'GeomLProp', 'LProp3d', 'TColGeom', 'TopAbs'],
                    'TKGeomBase': ['AdvApp2Var', 'AppCont', 'AppDef', 'AppParCurves', 'Approx', 'BndLib',
                                   'CPnts', 'Extrema', 'FEmTool', 'GC', 'GCE2d', 'GCPnts', 'Geom2dConvert',
                                   'GeomConvert', 'GeomLib', 'GeomProjLib', 'GeomTools', 'Hermit', 'IntAna',
                                   'IntAna2d', 'ProjLib', 'gce'],
                    'TKBO': ['BOPAlgo', 'BOPDS', 'BOPTools', 'BRepAlgoAPI', 'IntTools'],
                    'TKBool': ['BRepAlgo', 'BRepFill', 'BRepProj', 'TopOpeBRep', 'TopOpeBRepBuild',
                               'TopOpeBRepDS', 'TopOpeBRepTool'],
                    'TKFeat': ['BRepFeat', 'LocOpe'],
                    'TKFillet': ['BRepBlend', 'BRepFilletAPI', 'Blend', 'BlendFunc', 'ChFi2d', 'ChFi3d',
                                 'ChFiDS', 'ChFiKPart', 'FilletSurf'],
                    'TKGeomAlgo': ['AppBlend', 'ApproxInt', 'FairCurve', 'GccAna', 'GccEnt', 'GccInt',
                                   'Geom2dAPI', 'Geom2dGcc', 'Geom2dHatch', 'Geom2dInt', 'GeomAPI', 'GeomFill',
                                   'GeomInt', 'GeomPlate', 'Hatch', 'HatchGen', 'IntCurve', 'IntCurveSurface',
                                   'IntImp', 'IntImpParGen', 'IntPatch', 'IntPolyh', 'IntRes2d', 'IntStart',
                                   'IntSurf', 'IntWalk', 'Intf', 'Law', 'LocalAnalysis', 'NLPlate', 'Plate',
                                   'TopClass', 'TopTrans'],
                    'TKHLR': ['Contap', 'HLRAlgo', 'HLRAppli', 'HLRBRep', 'HLRTopoBRep', 'Intrv', 'TopBas',
                              'TopCnx'],
                    'TKMesh': ['BRepMesh', 'BRepMeshData', 'IMeshData', 'IMeshTools'],
                    'TKOffset': ['BRepOffset', 'BRepOffsetAPI', 'BiTgte', 'Draft'],
                    'TKPrim': ['BRepPrim', 'BRepPrimAPI', 'BRepSweep', 'Sweep'],
                    'TKShHealing': ['ShapeAlgo', 'ShapeAnalysis', 'ShapeBuild', 'ShapeConstruct', 'ShapeCustom',
                                    'ShapeExtend', 'ShapeFix', 'ShapeProcess', 'ShapeProcessAPI', 'ShapeUpgrade'],
                    'TKTopAlgo': ['BRepApprox', 'BRepBndLib', 'BRepBuilderAPI', 'BRepCheck', 'BRepClass',
                                  'BRepClass3d', 'BRepExtrema', 'BRepGProp', 'BRepIntCurveSurface', 'BRepLib',
                                  'BRepMAT2d', 'BRepTopAdaptor', 'Bisector', 'IntCurvesFace', 'MAT', 'MAT2d'],
                    'TKXMesh': ['XBRepMesh']}


TOOLKIT_Visualisation = {'TKService': ['Aspect', 'Image', 'InterfaceGraphic',
                                       'Media', 'TColQuantity'],
                         'TKV3d': ['AIS', 'DsgPrs', 'Graphic3d', 'Prs3d', 'PrsMgr',
                                   'Select3D', 'SelectBasics', 'SelectMgr', 'StdPrs',
                                   'StdSelect', 'V3d'],
                         # TKOpenGl not wrapped
                         'TKMeshVS': ['MeshVS']}


TOOLKIT_DataExchange = {'TKBinXCAF': ['BinMXCAFDoc', 'BinXCAFDrivers'],
                        'TKIGES': ['IGESControl', 'IGESData', 'IGESToBRep'],
                        'TKRWMesh' : ['RWGltf', 'RWObj'],
                        'TKSTEP': ['GeomToStep', 'RWStepAP203', 'RWStepAP214',
                                   'RWStepAP242', 'STEPConstruct', 'STEPControl',
                                   'STEPEdit', 'STEPSelections', 'StepAP203',
                                   'StepAP209', 'StepAP214', 'StepAP242', 'StepToGeom',
                                   'StepToTopoDS', 'TopoDSToStep'],
                        'TKSTEP209': ['RWStepElement', 'RWStepFEA', 'StepElement',
                                      'StepFEA'],
                        'TKSTEPAttr': ['RWStepDimTol', 'RWStepVisual', 'StepDimTol',
                                       'StepVisual'],
                        'TKSTEPBase': ['RWStepBasic', 'RWStepGeom', 'RWStepRepr', 'RWStepShape',
                                       'StepBasic', 'StepGeom', 'StepRepr', 'StepShape'],
                        'TKSTL': ['RWStl', 'StlAPI'],
                        'TKVRML': ['Vrml', 'VrmlAPI', 'VrmlConverter', 'VrmlData'],
                        'TKXCAF': ['XCAFApp', 'XCAFDimTolObjects', 'XCAFDoc', 'XCAFNoteObjects',
                                   'XCAFPrs', 'XCAFView'],
                        'TKXDEIGES': ['IGESCAFControl'],
                        'TKXDESTEP': ['STEPCAFControl'],
                        'TKXSBase': ['Interface', 'IFSelect', 'XSControl', 'Transfer',
                                     'TransferBRep', 'MoniTool', 'StepData'],
                        'TKXmlXCAF': ['XmlMXCAFDoc', 'XmlXCAFDrivers', ]}


TOOLKIT_OCAF = {'TKBin': ['BinDrivers', 'BinMDataXtd', 'BinMNaming'],
                'TKBinL': ['BinLDrivers', 'BinMDF', 'BinMDataStd', 'BinMDocStd',
                           'BinMFunction', 'BinObjMgt'],
                'TKBinTObj': ['BinTObjDrivers'],
                'TKCAF': ['TDataXtd', 'TNaming', 'AppStd'],
                'TKCDF': ['CDF', 'CDM', 'LDOM', 'PCDM', 'UTL'],
                'TKLCAF': ['TDF', 'TDataStd', 'TFunction', 'TDocStd', 'AppStdL'],
                # the two following packages need a deep investigation,
                # intensive use of templates
                #'TKStd': ['ShapePersistent', 'StdDrivers', 'StdObject', 'StdPersistent',
                #'StdStorage'],
                #'TKStdL': ['StdLDrivers', 'StdObjMgt', 'StdLPersistent'],
                'TKTObj': ['TObj'],
                'TKVAF': ['TPrsStd'],
                'TKXml': ['XmlDrivers', 'XmlMDataXtd', 'XmlMNaming'],
                'TKXmlL': ['XmlLDrivers', 'XmlMDF', 'XmlMDataStd', 'XmlMDocStd', 'XmlMFunction',
                           'XmlObjMgt'],
                'TKXmlTObj': ['XmlTObjDrivers']}

TOOLKIT_VTK = {'TKIVtk': ['IVtk', 'IVtkOCC', 'IVtkVTK', 'IVtkTools']}

# List of modules to export
#
# (string module_name, list additional headers, list classes_to_exclude,
# dict member_functions to exclude)

OCE_MODULES = [
    ###
    ### FOUNDATION
    ###
    ###
    ### TKernel
    ('FSD', [], ['*']),
    ('MMgt', [], []),
    ('Message', [], []),
    ('NCollection', ['gp'], ['*']),
    ('OSD', [], ['*']),
    ('Plugin', [], ['*']),
    ('Quantity', [], []),
    ('Resource', [], []),
    ('SortTools', [], []),
    ('Standard', [], ['Standard_AncestorIterator',
                      'Standard_Static_Assert',
                      'Standard_CLocaleSentry',
                      'Standard_Type', 'Standard_Failure',
                      'Standard_Mutex',
                      'Standard_ReadLineBuffer',
                      'Standard_ProgramError',
                      'Standard_ReadBuffer'], #occt720
     {'Standard_MMgrOpt': ['SetCallBackFunction'],
      'Standard': ['Free', 'FreeAligned'],
      'Standard_ErrorHandler': ['Label'],
      'Standard_ErrorHandlerCallback': ['RegisterCallback', 'UnregisterCallback'],
      'Standard_Condition': ['getHandle']}),
    ('StdFail', [], ['*']),
    ('Storage', ['Standard'], ['*']),
    ('TColStd', [], ['TColStd_PackedMapOfInteger']),
    ('TCollection', [], [],
     {'TCollection_ExtendedString': ['ToWideString']}),
    ('TShort', ['Standard'], []),
    ('Units', [], ['Units_Quantity', 'Units_Dimensions']),
    ('UnitsAPI', [], []),
    ('IncludeLibrary', [], ['*']),
    ### TKMath
    ('math', ['Adaptor3d', 'Precision'], ['math_SingleTab'],
     {'math_NewtonMinimum': ['IsConvex'],
      'math_NewtonFunctionSetRoot': ['StateNumber'],
      'math_GlobOptMin': ['isDone']}),
    ('ElCLib', [], []),
    ('ElSLib', [], []),
    ('BSplCLib', ['Message'], ['BSplCLib_EvaluatorFunction'], {'BSplCLib': ['DN']}),
    ('BSplSLib', [], ['BSplSLib_EvaluatorFunction']),
    ('PLib', ['Message'], []),
    ('Precision', [], []),
    ('GeomAbs', [], []),
    ('Poly', ['NCollection'],
     ['Poly_CoherentTriPtr', 'Poly_CoherentTriangulation',
      'Poly_MakeLoops', 'Poly_MakeLoops3D', 'Poly_MakeLoops2D'],
     {'Poly' : ['PolygonProperties']}),
    ('CSLib', ['Message'], []),
    ('Convert', [], []),
    ('Bnd', [], []),
    ('gp', [], [],
     {'gp_Torus': ['Coefficients'],
      'gp_Trsf': ['GetMat4']}),
    ('TColgp', ['Standard'], []),
    ('TopLoc', [], [],
     {'TopLoc_SListNodeOfSListOfItemLocation': ['Count'],
      'TopLoc_SListNodeOfItemLocation': ['Count']}),
    ('BVH', [], ['*']),
    ('Expr', [], ['Expr_Sign']),
    ('ExprIntrp', [], []),
    ###
    ### MODELING DATA
    ###
    ###
    ### TKG2d
    ('Geom2d', [], []),
    ('LProp', [], []),
    ('TColGeom2d', ['Standard'], []),
    ('Adaptor2d', [], []),
    ('Geom2dLProp', ['Message'], []),
    ('Geom2dAdaptor', [], []),
    ('GProp', [], []),
    ('Geom2dEvaluator', ['Adaptor2d', 'Geom2dAdaptor'], []),
    ### TKG3d
    ('Geom', [], []),
    ('TColGeom', ['Standard'], []),
    ('GeomAdaptor', ['Geom2d', 'Adaptor2d', 'Message'], []),
    ('AdvApprox', ['Message'], ['AdvApprox_EvaluatorFunction']),
    ('GeomLProp', [], []),
    ('Adaptor3d', ['Geom2d', 'Message'], []),
    ('LProp3d', ['Adaptor2d', 'Geom2d', 'Geom', 'Message'], []),
    ('TopAbs', [], []),
    ('GeomEvaluator', ['Geom2d', 'Adaptor2d', 'GeomAdaptor', 'Message'], []),
    ### TKGeomBase
    ('ProjLib', ['Message'], [],
     {'ProjLib_ProjectOnSurface': ['Load'],
      'ProjLib_ProjectedCurve': ['Load']}),
    ('GeomProjLib', [], []),
    ('GCPnts', ['Geom', 'Geom2d', 'Message'],
     ['GCPnts_DistFunction', 'GCPnts_DistFunction2d']),
    ('CPnts', ['Geom', 'Geom2d', 'Message'], []),
    ('Approx', ['FEmTool', 'Adaptor2d', 'Message'], []),
    ('AppParCurves', ['Message'], []),
    ('FEmTool', ['Message'], []),
    ('AppCont', ['Message'], []),
    ('Extrema', ['Precision', 'Message'], []),
    ('IntAna', [], []),
    ('IntAna2d', [], []),
    ('GeomConvert', ['Geom2d', 'Adaptor3d', 'Adaptor2d', 'Message'], [],
     {'GeomConvert_CompCurveToBSplineCurve': ['Clear']}),
    ('AdvApp2Var', ['PLib', 'Message'], ['AdvApp2Var_EvaluatorFunc2Var',
                                         'AdvApp2Var_Iso'],
     {'AdvApp2Var_MathBase': ['mmgaus1_']}),
    ('GeomLib', ['PLib', 'Adaptor2d', 'Precision', 'Message'], []),
    ('Geom2dConvert', ['Adaptor2d'], []),
    ('Hermit', ['Geom2d', 'Geom'], []),
    ('BndLib', ['Geom', 'Message'], []),
    ('AppDef', ['Adaptor2d', 'Adaptor3d', 'Geom', 'Geom2d', 'PLib',
                'Message'], [],
     {'AppDef_TheResol': ['Error'],
      'AppDef_ResConstraintOfTheGradient': ['Error'],
      'AppDef_ResConstraintOfMyGradientbisOfBSplineCompute': ['Error'],
      'AppDef_ResConstraintOfMyGradientOfCompute': ['Error'],
      'AppDef_MultiLine': ['SetParameter']}),
    ('GeomTools', ['TColStd', 'TColgp'], []),
    ('GC', [], []),
    ('GCE2d', [], []),
    ('gce', [], []),
    ### TKBRep
    ('TopoDS', [], [],),
    ('TopExp', ['Message', 'TopLoc'], []),
    ('TopTools', ['Message'], []),
    ('BRep', ['TShort', 'Message'], []),
    ('BRepLProp', ['GeomAdaptor', 'Geom', 'Geom2d', 'TopLoc',
                   'Adaptor3d', 'TopoDS', 'Adaptor2d',
                   'Geom2dAdaptor', 'Message'], []),
    ('BRepAdaptor', ['TopLoc', 'Geom2d', 'Message'], []),
    ('BRepTools', ['TShort', 'Poly'], [],
     {'BRepTools_ReShape': ['Merge'],
      'BRepTools_History': ['BRepTools_History', 'Merge']}),
    ('BinTools', ['Message', 'CDF'], [],
     {'BinTools_Curve2dSet': ['Dump']}), # Fixes undefined ref
    ### TKGeomAlgo
    ('Hatch', [], []),
    ('GeomInt', ['Bnd', 'IntAna', 'Adaptor2d',
                 'GeomAdaptor', 'Adaptor3d', 'Message'], ['GeomInt_WLApprox'],
     {'GeomInt_ResConstraintOfMyGradientbisOfTheComputeLineOfWLApprox': ['Error'],
      'GeomInt_ResConstraintOfMyGradientOfTheComputeLineBezierOfWLApprox': ['Error'],
      'GeomInt_IntSS': ['TolFixTangents', 'SetTolFixTangents'],
      'GeomInt_TheImpPrmSvSurfacesOfWLApprox': ['FillInitialVectorOfSolution']}),
    ('IntStart', [], []),
    ('IntWalk', ['Geom', 'Adaptor2d', 'Geom2d', 'IntSurf', 'Message'], []),
    ('IntImp', [], []),
    ('IntCurveSurface', ['Geom2d', 'Adaptor2d', 'Message'],
     ['IntCurveSurface_ThePolyhedronOfHInter']),
    ('IntSurf', ['Adaptor2d', 'Geom2d', 'Geom', 'Message'], []),
    ('IntPatch', ['Geom', 'Adaptor3d', 'Message'], ['IntPatch_Polyhedron'],
     {'IntPatch_RLine': ['SetParamOnS1', 'SetParamOnS2'],
      'IntPatch_ImpImpIntersection': ['GetStatus']}),
    ('Geom2dInt', ['Adaptor3d', 'Geom', 'Geom2d', 'GeomAdaptor', 'Message'], [],
     {'Geom2dInt_Geom2dCurveTool': ['IsComposite'],
      'Geom2dInt_TheCurveLocatorOfTheProjPCurOfGInter': ['Locate']}),
    ('IntImpParGen', [], ['IntImpParGen_ImpTool']),
    ('IntRes2d', [], []),
    ('IntCurve', ['Geom2d', 'Message'], []),
    ('TopTrans', [], []),
    ('Intf', [], []),
    ('ApproxInt', ['Adaptor3d', 'Geom', 'Adaptor2d', 'Geom2d', 'Message'], []),
    ('GccAna', [], []),
    ('GccEnt', [], []),
    ('GccInt', [], []),
    ('GccIter', [], []),
    ('HatchGen', [], []),
    ('Geom2dHatch', ['Adaptor3d', 'Geom2d',
                     'Intf', 'Extrema', 'Bnd', 'Geom',
                     'GeomAdaptor', 'Adaptor2d', 'Message'], [],
     {'Geom2dHatch_Hatcher': ['IsDone']}),
    ('Law', ['Adaptor2d', 'Geom', 'Geom2d', 'Message'], [],
     {'Law_Interpolate': ['ClearTangents']}),
    ('AppBlend', [], []),
    ('Plate', [], []),
    ('GeomPlate', ['PLib'], []),
    ('LocalAnalysis', ['Geom2d'], []),
    ('GeomAPI', ['Adaptor3d', 'Adaptor2d', 'GeomAdaptor',
                 'AppParCurves', 'Message'], [],
     {'GeomAPI_Interpolate': ['ClearTangents']}),
    ('GeomFill', ['Adaptor2d', 'FEmTool', 'AppParCurves', 'PLib',
                  'Message'],
     ['GeomFill_SweepSectionGenerator'],
     {'GeomFill_FunctionGuide': ['Deriv2T'],
      'GeomFill_NSections': ['GeomFill_NSections::637af4a0f33ec19afb7aacd41d59fa97'],
      }),
    ('Geom2dAPI', ['GeomAdaptor', 'Geom', 'Adaptor2d', 'Adaptor3d', 'Bnd',
                   'AppParCurves', 'Message'], [],
     {'Geom2dAPI_Interpolate': ['ClearTangents']}),
    ('Geom2dGcc', ['GccInt', 'Adaptor2d', 'Message'], ['Geom2dGcc_FunctionTanCuCuCu'],
     {'Geom2dGcc_Lin2dTanObl': ['IsParallel2']}),
    ('FairCurve', ['Message'], []),
    ('NLPlate', ['Message'], []),
    ('IntPolyh', ['Geom', 'Geom2d', 'Adaptor2d', 'Message'],
     ['IntPolyh_Array',
      'IntPolyh_MaillageAffinage'],
     {'IntPolyh_Triangle': ['GetNextChainTriangle']}),
    ('TopClass', ['Adaptor3d', 'IntSurf', 'TopLoc', 'Geom2d',
                  'Geom', 'Adaptor2d', 'Message', 'Bnd'], []),
    ### TKTopALgo
    ('IntCurvesFace', ['TopLoc', 'IntSurf', 'Geom', 'Geom2d',
                       'Adaptor2d', 'Message'], []),
    ('MAT', [], []),
    ('MAT2d', ['Geom2d', 'Message'], ['MAT2d_SketchExplorer', 'MAT2d_CutCurve']),
    ('Bisector', ['Message'], []),
    ('BRepMAT2d', ['TopLoc', 'Message', 'Geom2d'], []),
    ('BRepCheck', ['TopLoc', 'Message', 'Geom2d', 'Geom', 'Adaptor3d',
                   'Adaptor2d'], []),
    ('BRepBndLib', ['TopLoc', 'Message'], []),
    ('BRepExtrema', ['GeomAdaptor', 'Geom', 'Geom2d', 'Adaptor3d',
                     'Adaptor2d', 'TopLoc', 'Message'], ['BRepExtrema_OverlapTool'],
     {'BRepExtrema_SelfIntersection': ['OverlapTriangles']}),
    ('BRepClass',
     ['Geom2d', 'TopLoc', 'Adaptor2d', 'Extrema',
      'Geom', 'GeomAdaptor', 'Adaptor3d', 'Message', 'Bnd'],
     ['BRepClass_FaceClassifier']),
    ('BRepClass3d',
     ['TopLoc', 'GeomAdaptor', 'IntSurf',
      'Adaptor3d', 'Geom', 'Geom2d', 'Adaptor2d',
      'Geom2dAdaptor', 'Message', 'Bnd'],
     ['BRepClass3d_BndBoxTreeSelectorLine',
      'BRepClass3d_BndBoxTreeSelectorPoint']),
    ('BRepLib',
     ['TopoDS', 'Adaptor2d', 'BRep', 'Message', 'Bnd', 'Poly', 'TShort'], [],
     {'BRepLib' : ['BuildPCurveForEdgesOnPlane']}),
    ('BRepGProp',
     ['Adaptor3d', 'TopLoc', 'Geom2dAdaptor', 'Geom', 'Geom2d',
      'Adaptor2d', 'GeomAdaptor', 'Message', 'Bnd', 'TShort'],
     ['BRepGProp_MeshProps'],
     {'BRepGProp_VinertGK': ['GetAbsolutError'],
      'BRepGProp_Gauss': ['Compute']}),
    ('BRepIntCurveSurface',
     ['Bnd', 'TopLoc', 'IntSurf', 'Adaptor2d', 'Geom2d',
      'Adaptor3d', 'Geom', 'Message'], []),
    ('BRepTopAdaptor', ['Geom', 'Geom2d', 'GeomAdaptor',
                        'TopLoc', 'Geom2dAdaptor', 'Message'], []),
    ('BRepBuilderAPI', ['BRep', 'TopLoc', 'TShort', 'Poly'], [],
     {'BRepBuilderAPI_FastSewing': ['GetStatuses'],
      'BRepBuilderAPI_CellFilter': ['Remove']}),
    ('BRepApprox',
     ['TopLoc', 'TopoDS', 'FEmTool', 'GeomAdaptor',
      'Geom2dAdaptor', 'Adaptor3d', 'Adaptor2d', 'Message'], [],
     {'BRepApprox_ResConstraintOfMyGradientbisOfTheComputeLineOfApprox': ['Error'],
      'BRepApprox_ResConstraintOfMyGradientOfTheComputeLineBezierOfApprox': ['Error'],
      'BRepApprox_Approx': ['Perform'],
      'BRepApprox_TheImpPrmSvSurfacesOfApprox': ['FillInitialVectorOfSolution']}),
    ### TKPrim
    ('BRepPrim', ['TopLoc', 'Message', 'Poly', 'TShort'], []),
    ('BRepSweep', ['Geom', 'Geom2d', 'TShort', 'Poly', 'Message'], []),
    ('Sweep', [], []),
    ('BRepPrimAPI',
     ['TopLoc', 'Geom2d', 'BRep', 'Message', 'BRepTools', 'Bnd', 'Poly', 'TShort'], []),
    ### TKBO
    ('IntTools',
     ['AppParCurves', 'IntRes2d', 'Geom2dInt',
      'Adaptor3d', 'FEmTool', 'Extrema', 'IntAna',
      'Intf', 'IntSurf', 'BRepAdaptor', 'Quantity',
      'HatchGen', 'TopLoc', 'Approx', 'BRepClass3d',
      'IntCurveSurface', 'Geom2dHatch', 'GeomAdaptor',
      'Geom2dAdaptor', 'Adaptor2d', 'Message', 'TopTools'],
     ['IntTools_CArray1OfInteger',
      'IntTools_CArray1OfReal'],
     {'IntTools_PntOnFace': ['IsValid']}),
    ('BRepAlgoAPI', ['TopLoc', 'BRepAdaptor', 'IntTools', 'GeomAdaptor', 'Geom2d',
                     'Geom2dAdaptor', 'Extrema', 'Adaptor2d', 'IntSurf', 'BOPDS',
                     'IntPatch', 'Approx', 'Adaptor3d', 'Message', 'AppParCurves',
                     'Bnd', 'BRep', 'TShort', 'Poly'], []),
    ('BOPCol', [], ['BOPCol_Array1', 'BOPCol_MemBlock',
                    'BOPCol_NCVector', 'BOPCol_TBBCnt',
                    'BOPCol_TBBContextCnt', 'BOPCol_TBBContextFunctor',
                    'BOPCol_TBBFunctor',
                    # Problems parsing template parameters on classes
                    'BOPCol_Functor', 'BOPCol_Cnt', 'BOPCol_Cnt_Perform',
                    'BOPCol_ContextFunctor', 'BOPCol_ContextCnt']),
    ('BOPDS', ['IntTools', 'AppParCurves', 'Adaptor2d',
               'Adaptor3d', 'FEmTool', 'Extrema', 'IntAna',
               'Intf', 'IntSurf', 'BRepAdaptor', 'Quantity',
               'HatchGen', 'TopLoc', 'Approx', 'Geom2dHatch',
               'IntRes2d', 'Geom', 'Geom2d', 'BRepClass3d',
               'IntCurveSurface', 'GeomAdaptor', 'Geom2dInt',
               'Geom2dAdaptor', 'IntPatch', 'Message', 'TopTools'], ['BOPDS_Interf'],
     {'BOPDS_CoupleOfPaveBlocks': ['Handle']}),
    ('BOPAlgo', ['Geom2d', 'Extrema', 'BRepAdaptor', 'Adaptor2d',
                 'Adaptor3d', 'GeomAdaptor', 'TopLoc', 'Approx', 'IntPatch',
                 'Geom', 'Geom2dAdaptor', 'AppParCurves', 'Bnd',
                 'IntTools', 'BRep', 'TShort', 'Poly'], [],
     {'BOPAlgo_PaveFiller': ['Iterator'],
      'BOPAlgo_Tools': ['MakeBlocks', 'FillMap']}),
    ('BOPTools',
     ['Extrema', 'Adaptor2d', 'Approx', 'Adaptor3d',
      'GeomAdaptor', 'IntPatch', 'TopLoc', 'Geom2dAdaptor',
      'Message', 'TopTools', 'AppParCurves', 'Bnd'],
     ['BOPTools_Parallel', 'BOPTools_BoxSelector', 'BOPTools_BoxSet',
      'BOPTools_PairSelector'],
     {'BOPTools_AlgoTools2D': ['MakeCurveOnSurface'],
      'BOPTools_BoxSelector': ['Accept', 'AcceptMetric']}),
    ### TKHLR
    ('HLRTopoBRep', ['TColStd', 'TColgp', 'BRepAdaptor',
                     'TopLoc', 'IntSurf', 'GeomAdaptor', 'Geom',
                     'Adaptor3d', 'Message', 'Geom2dAdaptor',
                     'Adaptor2d'], []),
    ('HLRBRep', ['Message', 'Contap', 'GeomAdaptor', 'TopLoc',
                 'Geom2dAdaptor', 'Adaptor2d', 'Adaptor3d'],
     ['HLRBRep_ThePolyhedronOfInterCSurf', 'HLRBRep_BSurfaceTool',
      'HLRBRep_Surface', 'HLRBRep_TheCurveLocatorOfTheProjPCurOfCInter']),
    ('HLRAlgo', ['gp'], ['HLRAlgo_TriangleData', 'HLRAlgo_PolyInternalSegment',
                         'HLRAlgo_PolyHidingData'],
     {'HLRAlgo_BiPoint': ['Indices', 'Points'],
      'HLRAlgo_EdgesBlock': ['UpdateMinMax'],
      'HLRAlgo_PolyData': ['UpdateGlobalMinMax', 'HideByPolyData', 'Indices'],
      'HLRAlgo_PolyHidingData': ['Indices', 'Plane'],
      'HLRAlgo_PolyInternalNode': ['Indices', 'Data'],
      'HLRAlgo_PolyShellData': ['Indices']},),
    ('HLRAppli', ['Adaptor2d', 'Geom2dAdaptor', 'GeomAdaptor', 'BRepAdaptor',
                  'Geom', 'Geom2d', 'Adaptor3d', 'Extrema', 'IntSurf', 'HLRAlgo',
                  'BRepTopAdaptor', 'HLRTopoBRep', 'TopLoc', 'Contap',
                  'Message', 'Bnd', 'TopTools'], []),
    ('Intrv', [], []),
    ('TopBas', ['Message'], []),
    ('TopCnx', [], []),
    ('Contap', ['TColgp', 'Geom', 'NCollection', 'Adaptor3d', 'Message'], []),
    ### TKMesh
    ('BRepMesh', ['TShort', 'Adaptor3d', 'Geom2dAdaptor', 'Message',
                  'Adaptor2d', 'GeomAdaptor', 'Geom', 'TopLoc',
                  'Geom2d'],
     ['BRepMesh_WireInterferenceChecker', 'BRepMesh_EdgeTessellator',
      'BRepMesh_EdgeTessellationExtractor', 'BRepMesh_EdgeParameterProvider',
      'BRepMesh_FastDiscret', 'BRepMesh_CustomDelaunayBaseMeshAlgo',
      'BRepMesh_NodeInsertionMeshAlgo', 'BRepMesh_ConstrainedBaseMeshAlgo',
      'BRepMesh_CustomBaseMeshAlgo', 'BRepMesh_DelaunayDeflectionControlMeshAlgo',
      'BRepMesh_DelaunayNodeInsertionMeshAlgo'],
     {'BRepMesh_MeshTool': ['DumpTriangles', 'EraseTriangles'],
      'BRepMesh_Delaun': ['Frontier', 'InternalEdges', 'FreeEdges', 'ProcessConstraints'],
      'BRepMesh_GeomTool': ['IntLinLin', 'Normal', 'IntSegSeg']},
    ),
    ('BRepMeshData', ['Geom', 'Geom2d', 'GeomAdaptor', 'Geom2dAdaptor', 'Adaptor3d',
                      'Adaptor2d', 'BRepAdaptor', 'Message'], [],
     {'BRepMeshData_Curve':'BRepMeshData_Curve',
      'BRepMeshData_Edge':'BRepMeshData_Edge',
      'BRepMeshData_Face':'BRepMeshData_Face',
      'BRepMeshData_PCurve':'BRepMeshData_PCurve',
      'BRepMeshData_Wire':'BRepMeshData_Wire'}),
    ('IntPoly', ['TColStd', 'TopLoc'], []),
    ('IMeshData', ['Geom', 'Geom2d', 'GeomAdaptor', 'Geom2dAdaptor', 'Adaptor3d',
                   'Adaptor2d', 'Message'], []),
    ('IMeshTools', ['Geom', 'Geom2d', 'GeomAdaptor', 'Geom2dAdaptor', 'Adaptor3d',
                    'Adaptor2d', 'BRepAdaptor'], []),
    ### TKShHealing
    ('ShapeBuild', ['TShort', 'TColGeom', 'BRep', 'Message',
                    'TopTools', 'Bnd', 'TCollection',
                    'Poly', 'Geom'], []),
    ('ShapeExtend', ['TColgp', 'TopLoc', 'Poly', 'IntRes2d',
                     'BRepBuilderAPI', 'GeomAdaptor'], []),
    ('ShapeConstruct', ['TCollection', 'BRep', 'Bnd', 'Adaptor2d',
                        'TColGeom', 'Adaptor3d', 'TopLoc',
                        'TShort', 'Message', 'Poly', 'BRepTools',
                        'IntRes2d', 'BRepBuilderAPI', 'GeomAdaptor',
                        'ShapeAnalysis', 'Geom', 'TopTools'], []),
    ('ShapeCustom',
     ['BRep', 'Message', 'Poly', 'TShort', 'Bnd', 'TColGeom', 'ShapeExtend',
      'TopTools'],
     ['ShapeCustom_BSplineRestriction',
      'ShapeCustom_SweptToElementary',
      'ShapeCustom_ConvertToRevolution'],
     {'ShapeCustom' : ['ApplyModifier']}),
    ('ShapeAnalysis', ['TColGeom', 'Message', 'Adaptor2d', 'Geom'],
     ['ShapeAnalysis_BoxBndTreeSelector',
      'ShapeCustom_ConvertToRevolution']),
    ('ShapeFix', ['TColGeom', 'BRep', 'TShort',
                  'Adaptor3d', 'Poly', 'BRepTools', 'Adaptor2d',
                  'IntRes2d', 'BRepBuilderAPI', 'GeomAdaptor', 'Bnd',
                  'Geom'],
     ['ShapeFix_WireSegment'],
     {'ShapeFix_Edge': ['Context']}),
    ('ShapeUpgrade', ['BRep', 'Bnd', 'TShort', 'Adaptor3d',
                      'TCollection', 'Message', 'Poly', 'BRepTools',
                      'IntRes2d', 'BRepBuilderAPI', 'GeomAdaptor',
                      'Adaptor2d', 'Precision', 'Geom'], []),
    ('ShapeAlgo', ['Geom', 'TopTools', 'BRep', 'TColGeom', 'TopLoc',
                   'Message', 'Bnd', 'Geom2d', 'ShapeAnalysis',
                   'TShort', 'ShapeExtend', 'Adaptor3d',
                   'Poly', 'TopoDS', 'BRepTools', 'IntRes2d',
                   'BRepBuilderAPI', 'GeomAdaptor', 'Adaptor2d',
                   'ShapeConstruct', 'ShapeBuild'],
     ['ShapeAlgo_AlgoContainer']),
    ('ShapeProcess', ['BRep', 'TShort', 'TColGeom', 'Poly', 'Message',
                      'Bnd', 'Geom2d', 'Geom', 'TopLoc', 'ShapeExtend'], []),
    ('ShapeProcessAPI', ['BRep', 'ShapeExtend', 'Geom', 'Geom2d',
                         'TopLoc', 'Geom2d', 'BRepTools', 'Message', 'TShort',
                         'Resource', 'ShapeBuild', 'Bnd', 'Poly', 'TColGeom'], []),
    ### TKXMesh
    ('XBRepMesh', ['Adaptor2d', 'Geom2dAdaptor', 'Geom', 'BRepAdaptor',
                   'GeomAdaptor', 'Geom2d', 'TopLoc', 'Adaptor3d',
                   'Message', 'Bnd', 'Poly', 'TShort', 'IMeshTools'], []),
    ### TKBool
    ('TopOpeBRep', ['TColStd', 'TCollection', 'TopLoc', 'TColgp',
                    'Adaptor3d', 'IntAna', 'Message', 'IntSurf',
                    'Extrema', 'IntCurveSurface', 'Geom2d', 'Geom2dAdaptor',
                    'BRepAdaptor', 'GeomAdaptor', 'Adaptor2d'],
     ['TopOpeBRep_traceSIFF'],
     {'TopOpeBRep_FacesFiller': ['EqualpP'],
      'TopOpeBRep_EdgesIntersector': ['Tolerance2'],
      'TopOpeBRep_GeomTool': ['MakePrivateCurves']}),
    ('TopOpeBRepDS', ['TopLoc', 'TColgp', 'Adaptor2d', 'Bnd',
                      'BRepAdaptor', 'Adaptor3d', 'Intf',
                      'Message', 'IntSurf', 'Extrema',
                      'IntCurveSurface', 'Geom2d', 'Geom2dAdaptor',
                      'BRepAdaptor', 'GeomAdaptor'],
     ['TopOpeBRepDS_DSS', 'TopOpeBRepDS_HDataStructure'],
     {'TopOpeBRepDS_Dumper': ['Print']}),
    ('TopOpeBRepBuild', ['Geom', 'Adaptor2d', 'Bnd',
                         'BRepAdaptor', 'TopLoc', 'Adaptor3d',
                         'Message', 'Intf', 'IntSurf', 'Extrema',
                         'IntCurveSurface', 'Geom2d', 'Geom2dAdaptor',
                         'BRepAdaptor', 'GeomAdaptor'], [],
     {'TopOpeBRepBuild_Builder1': ['GFillSplitsPVS']}),
    ('TopOpeBRepTool', ['Geom', 'Adaptor2d', 'Bnd',
                        'BRepAdaptor', 'TopLoc', 'Adaptor3d',
                        'Message', 'Intf', 'IntSurf', 'Extrema',
                        'IntCurveSurface', 'Geom2d', 'Geom2dAdaptor',
                        'BRepAdaptor', 'GeomAdaptor'],
     ['TopOpeBRepTool_STATE', 'TopOpeBRepTool_mkTondgE']),
    ('BRepAlgo', ['TopExp', 'TopLoc', 'IntSurf', 'BRep',
                  'TopOpeBRepDS', 'Bnd', 'Message',
                  'TShort', 'Intf', 'TopOpeBRepTool',
                  'Poly', 'Extrema', 'BRepTools', 'IntCurveSurface',
                  'Geom2d', 'Geom2dAdaptor', 'BRepAdaptor',
                  'GeomAdaptor', 'Adaptor2d'], [],
     {'BRepAlgo_DSAccess': ['IsDeleted']}),
    ('BRepFill', ['FEmTool', 'TColGeom2d', 'PLib', 'TopLoc',
                  'Plate', 'AdvApp2Var', 'TColGeom',
                  'Message', 'Convert', 'Approx', 'Adaptor2d', 'MAT',
                  'Geom2d', 'Geom', 'Adaptor3d'], []),
    ('BRepProj', ['TopLoc', 'Message'], []),
    ### TKFillet
    ('ChFiDS', ['Message', 'TopLoc', 'GeomAdaptor',
                'Geom2dAdaptor', 'IntCurveSurface',
                'Adaptor2d', 'Adaptor3d'], []),
    ('ChFi2d', ['TopLoc', 'Message'], []),
    ('ChFi3d', ['math', 'Extrema', 'IntCurveSurface', 'TopLoc', 'Message',
                'Approx', 'Adaptor2d', 'TopOpeBRepTool', 'Geom2dAdaptor',
                'TColGeom', 'AppParCurves', 'Adaptor3d'], []),
    ('ChFiKPart', ['TopTools', 'TColStd', 'TColgp',
                   'BRepAdaptor', 'Geom', 'Bnd', 'BRepClass3d',
                   'TopoDS', 'gp', 'TopLoc', 'Message',
                   'Intf', 'IntSurf', 'TopOpeBRepTool',
                   'Law', 'Extrema', 'IntCurveSurface',
                   'Geom2dAdaptor', 'Adaptor2d', 'Adaptor3d'], []),
    ('Blend', ['Geom2d', 'Message'], []),
    ('BRepBlend',
     ['AppParCurves', 'TCollection', 'PLib', 'FEmTool',
      'Convert', 'Geom', 'Geom2d', 'Message',
      'BRepAdaptor', 'GeomAdaptor', 'Geom2dAdaptor',
      'TopLoc', 'TopoDS', 'TopTools', 'Adaptor3d', 'Adaptor2d'], [],
     {'BRepBlend_AppSurface': ['TolReached']}),
    ('BlendFunc', ['Geom2d', 'Geom', 'Message'], [],
     {'BlendFunc': ['Mults', 'Knots']}),
    ('BRepFilletAPI', ['Adaptor3d', 'GeomAdaptor', 'Geom2d',
                       'GeomFill', 'BRep', 'Geom2d',
                       'BRepAdaptor', 'Adaptor2d', 'BRepTools',
                       'Approx', 'TopLoc', 'TopOpeBRepDS',
                       'Extrema', 'Approx', 'BRepBlend', 'Message',
                       'TopOpeBRepTool', 'Geom2dAdaptor', 'BRepAdaptor',
                       'AppParCurves', 'Bnd', 'Poly', 'TColGeom', 'TShort'], []),
    ('FilletSurf', ['TopoDS', 'TopOpeBRepDS', 'GeomAdaptor', 'BRepAdaptor', 'Extrema',
                    'Law', 'GeomFill', 'TopLoc', 'ChFiDS', 'BRepBlend', 'TopOpeBRepTool',
                    'Approx', 'TopOpeBRepBuild', 'Adaptor2d', 'Geom2dAdaptor', 'Adaptor3d',
                    'Message', 'AppParCurves', 'Bnd', 'TColGeom'], []),
    ### TKFeat
    ('LocOpe', ['TColStd', 'Bnd', 'BRepAdaptor',
                'BRepClass3d', 'Adaptor3d', 'TopLoc',
                'Intf', 'Message', 'IntSurf',
                'TopOpeBRepTool', 'Extrema', 'Geom2d',
                'IntCurveSurface', 'GeomAdaptor', 'Geom2dAdaptor'],
     ['LocOpe_Revol', 'LocOpe_RevolutionForm']),
    ('BRepFeat', ['TopLoc', 'BRepAdaptor', 'Adaptor3d', 'GeomAdaptor',
                  'BRepTools', 'BOPDS', 'Adaptor2d', 'IntSurf', 'IntTools',
                  'Geom2dAdaptor', 'Approx', 'IntPatch', 'Geom2d', 'TShort',
                  'BRep', 'Extrema', 'Message', 'AppParCurves', 'Bnd', 'Poly'], [],
     {'BRepFeat': ['IsInOut'],
      'BRepFeat_MakeLinearForm': ['TransformShapeFU']}),
    ### TKOffset
    ('BRepOffsetAPI', ['Bnd', 'AppParCurves', 'MAT', 'TColgp',
                       'BRepAlgo', 'FEmTool', 'TopOpeBRepBuild',
                       'Plate', 'Bisector', 'TColStd', 'PLib',
                       'BRepMAT2d', 'TColGeom2d', 'BRepAdaptor',
                       'BRepClass3d', 'BRep', 'BRepTools',
                       'Quantity', 'Adaptor3d', 'TopLoc',
                       'AdvApp2Var', 'TColGeom', 'IntSurf',
                       'Message', 'Convert', 'Intf', 'TShort',
                       'TopOpeBRepDS', 'Poly', 'TopOpeBRepTool',
                       'Extrema', 'Geom2d', 'IntCurveSurface',
                       'GeomAdaptor', 'Geom2dAdaptor',
                       'BRepBuilderAPI', 'GeomPlate', 'Adaptor2d',
                       'Geom', 'BRepAlgo'], [],
     {'BRepOffsetAPI_FindContigousEdges': ['NbEdges']}),
    ('BRepOffset', ['Quantity', 'Bnd', 'AppParCurves', 'MAT', 'TColgp',
                    'BRepAlgo', 'FEmTool', 'TopOpeBRepBuild',
                    'Plate', 'Bisector', 'TColStd',
                    'BRepMAT2d', 'TColGeom2d', 'BRepAdaptor',
                    'BRepClass3d', 'BRep', 'BRepTools',
                    'Quantity', 'Adaptor3d', 'TopLoc',
                    'AdvApp2Var', 'TColGeom', 'IntSurf',
                    'Message', 'Convert', 'Intf', 'TShort',
                    'TopOpeBRepDS', 'Poly', 'TopOpeBRepTool',
                    'Extrema', 'Geom2d', 'IntCurveSurface',
                    'GeomAdaptor', 'Geom2dAdaptor',
                    'BRepBuilderAPI', 'Adaptor2d'], [],
     {'BRepOffset_MakeOffset': ['GetAnalyse'],
      'BRepOffset_MakeSimpleOffset': ['GetSafeOffset']}),
    ('Draft', ['BRep', 'Bnd', 'TShort', 'Message', 'Poly'], []),
    ('BiTgte', ['TopLoc', 'Message', 'Adaptor2d'], []),
    ###
    ### Visualisation
    ###
    ###
    ### TKService
    ('Aspect',
     [],
     ['Aspect_CircularGrid',
      'Aspect_NeutralWindow', 'Aspect_RectangularGrid'],
     {'Aspect_DisplayConnection': ['Aspect_DisplayConnection', 'GetAtom', 'GetDisplay',
                                   'GetDisplayName', 'Init', 'IsOwnDisplay'],
      'Aspect_Window': ['NativeHandle', 'NativeParentHandle']}),
    ('Media', ['Geom', 'Bnd', 'Quantity', 'Aspect'], []),
    ('Image', [], ['*']),
    ('InterfaceGraphic', [], []),
    ('TColQuantity', [], []),
    ### TKV3d
    ('V3d',
     ['TShort', 'TColQuantity', 'Bnd', 'Geom', 'BVH', 'TColgp', 'TopTools',
      'SelectMgr', 'Poly', 'HLRAlgo', 'Select3D', 'Media'], [],
     {'V3d_Viewer': ['Print'],
      'V3d_View': ['Print']}),
    ('Graphic3d',
     ['TShort', 'TColQuantity', 'BVH', 'TopTools', 'SelectMgr',
      'HLRAlgo', 'Poly', 'V3d'],
     ['Graphic3d_UniformValue', 'Graphic3d_UniformValueType',
      'Graphic3d_UniformValueTypeID', 'Graphic3d_Buffer',
      'Graphic3d_IndexBuffer', 'Graphic3d_TransformPers', 'Graphic3d_TextureSet',
      'Graphic3d_CubeMapOrder', 'Graphic3d_CubeMapPacked', 'Graphic3d_BvhCStructureSetTrsfPers'],
     {'Graphic3d_ShaderVariable': ['Create'],
      'Graphic3d_ValueInterface': ['As'],
      'Graphic3d_ShaderProgram': ['PushVariable'],
      'Graphic3d_Group': ['SetGroupPrimitivesAspect'],
      'Graphic3d_GraphicDriver': ['Print'],
      'Graphic3d_Layer': ['FrustumCullingBVHBuilder', 'Graphic3d_Layer',  # to avoid circular dep #60
                          'SetFrustumCullingBVHBuilder'],
      'Graphic3d_BvhCStructureSet': ['Graphic3d_BvhCStructureSet', 'Add', 'Clear', 'GetStructureById', 'Remove'],
      'Graphic3d_MediaTextureSet' : ['SetCallback']}),
    ('Select3D', ['TShort', 'TColQuantity', 'Aspect',
                  'Graphic3d', 'Quantity', 'Message', 'TopLoc', 'V3d', 'TopTools',
                  'Poly', 'HLRAlgo', 'Prs3d', 'TopoDS', 'Media'],
     ['Select3D_SensitiveTriangulation', 'Select3D_SensitiveEntity',
      'Handle_Select3D_SensitiveEntity', 'Select3D_SensitiveSet'],
     {'Select3D_SensitiveBox': ['Box']}),
    ('Prs3d', ['TShort', 'TColQuantity', 'Message', 'BVH', 'V3d',
               'Geom', 'SelectMgr', 'Select3D', 'Media'],
     ['Prs3d_WFShape', 'Prs3d_Point']),
    ('StdPrs',
     ['Adaptor3d', 'GeomAdaptor', 'Message', 'Geom2d',
      'Geom2dAdaptor', 'Graphic3d',
      'Quantity', 'TopTools', 'TShort', 'Aspect', 'V3d',
      'SelectMgr', 'Select3D', 'Media'],
     ['StdPrs_DeflectionCurve']),
    ('SelectMgr', ['TopTools', 'Message', 'TShort', 'SelectBasics',
                   'gp', 'HLRAlgo', 'TColQuantity', 'Geom', 'Aspect',
                   'Poly', 'TopoDS', 'V3d', 'Select3D', 'Graphic3d', 'Quantity',
                   'BVH', 'Prs3d', 'Media'],
     ['SelectMgr_Frustum', 'SelectMgr_FrustumBuilder', 'SelectMgr_BaseFrustum',
      'SelectMgr_TriangularFrustum', 'SelectMgr_RectangularFrustum',
      'SelectMgr_TriangularFrustumSet', 'SelectMgr_ToleranceMap',
      'SelectMgr_ViewerSelector', 'SelectMgr_SensitiveEntitySet'],
     {'SelectMgr_SelectableObject': ['BndBoxOfSelected'],
      'SelectMgr_SelectingVolumeManager': ['ActiveVolume']},),
    ('SelectBasics', ['Bnd', 'Geom', 'Select3D', 'Graphic3d', 'Aspect',
                      'Quantity'], []),
    ('PrsMgr',
     ['gp', 'HLRAlgo', 'TopoDS', 'Aspect', 'TShort', 'Media',
      'Message', 'Bnd', 'TopTools', 'TColQuantity', 'Poly',
      'TopLoc', 'Quantity', 'BVH', 'SelectMgr', 'Select3D'], [], {}),
    ('AIS', ['TopTools', 'Message', 'TShort',
             'SelectBasics', 'HLRAlgo', 'TColQuantity',
             'SelectMgr'], [],
     {'AIS_LocalContext': ['Reactivate', 'Status'],
      'AIS_Dimension' : ['AIS_Dimension'],
      'AIS_TexturedShape': ['ShowTriangles'],
      'AIS_InteractiveContext': ['EntityOwners', 'Status'],
      'AIS_Manipulator': ['TransformBehavior', 'ChangeTransformBehavior',
                          'SetTransformBehavior']}),
    ('DsgPrs', [], ['*']),
    ('StdSelect', ['Bnd', 'TShort', 'HLRAlgo', 'Poly', 'TopTools',
                   'Quantity', 'TopTools', 'Message', 'Media'], []),
    # MeshVS
    ('MeshVS', ['TopTools', 'Message', 'TShort',
                'Geom', 'HLRAlgo', 'Poly',
                'TColQuantity', 'TopoDS', 'V3d',
                'TopLoc', 'Prs3d', 'StdSelect', 'Media'], []),
    ###
    ### DataExchange
    ###
    ## TKStl
    ('StlAPI', ['Message', 'TopLoc'], []),
    ('RWStl', ['TShort'], ['RWStl_Reader']),
    ### TKSTEPBase
    ('StepData', ['MoniTool', 'TopoDS'], ['StepData_FreeFormEntity', 'StepData_UndefinedEntity'],
     {'StepData_StepReaderData': ['ReadMember', 'ReadEntity']}),
    ('StepBasic', ['MoniTool', 'TCollection', 'StepBasic',
                   'Message', 'Interface', 'TopoDS'], []),
    ('RWStepBasic', ['MoniTool', 'TCollection', 'StepBasic',
                     'Message', 'TopoDS'], []),
    ('StepRepr',
     ['MoniTool', 'TCollection', 'Interface', 'StepBasic',
      'Message', 'StepData', 'StepGeom', 'StepShape', 'TopoDS'],
     ['StepRepr_ReprItemAndMeasureWithUnitAndQRI']),
    ('RWStepRepr', ['MoniTool', 'TCollection', 'Interface', 'StepBasic',
                    'StepData', 'Message', 'StepShape', 'StepGeom', 'TopoDS'], []),
    ('StepGeom', ['MoniTool', 'TCollection', 'Interface', 'StepBasic',
                  'Message', 'StepShape', 'TopoDS'], []),
    ('RWStepGeom', ['MoniTool', 'TCollection', 'StepBasic',
                    'StepData', 'Message', 'StepShape', 'StepRepr', 'TopoDS'], []),
    ('StepShape', ['MoniTool', 'TCollection', 'Interface', 'StepBasic',
                   'Message', 'TopoDS'], []),
    ('RWStepShape', ['MoniTool', 'TCollection', 'Interface', 'StepBasic',
                     'Message', 'StepGeom', 'StepRepr', 'TopoDS'], []),
    ### TKSTEP
    ('StepAP214', ['Message', 'StepBasic', 'StepData', 'StepShape',
                   'StepRepr', 'StepGeom', 'Interface', 'MoniTool', 'TopoDS'], []),
    ('RWStepAP214', ['Message', 'StepRepr', 'StepGeom', 'StepBasic',
                     'StepShape', 'StepVisual', 'MoniTool', 'TopoDS'], []),
    ('StepAP203', ['Message', 'StepBasic', 'Interface', 'StepShape',
                   'StepGeom', 'MoniTool', 'TopoDS'], []),
    ('RWStepAP203', ['Message', 'StepBasic', 'StepData', 'StepGeom', 'StepShape',
                     'StepRepr', 'MoniTool', 'TopoDS'], []),
    ('StepAP242', ['Message', 'StepBasic', 'Interface', 'StepShape',
                   'StepGeom', 'StepVisual', 'MoniTool', 'TopoDS'], []),
    ('RWStepAP242', ['Message', 'StepBasic', 'Interface', 'StepShape',
                     'StepGeom', 'StepRepr', 'StepVisual', 'StepAP214', 'StepDimTol',
                     'MoniTool', 'TopoDS'], []),
    ('STEPConstruct', ['TopTools', 'IFSelect', 'Message', 'StepBasic',
                       'Geom2d', 'Geom', 'StepData', 'StepShape',
                       'MoniTool'], []),
    ('STEPEdit', ['Message', 'StepBasic', 'StepData',
                  'Interface', 'MoniTool', 'TopoDS'], []),
    ('GeomToStep', ['Message', 'StepBasic', 'StepBasic', 'StepGeom',
                    'StepRepr', 'Geom2d', 'Geom', 'MoniTool',
                    'StepElement', 'Interface', 'StepData', 'StepShape',
                    'TopoDS'], []),
    ('StepToGeom', ['Message', 'StepShape', 'StepBasic', 'StepGeom', 'StepRepr',
                    'StepElement', 'Interface', 'StepData', 'MoniTool', 'TopoDS'], []),
    ('StepToTopoDS', ['Message', 'StepBasic', 'Interface', 'TopLoc',
                      'Transfer', 'StepData', 'MoniTool', 'TopoDS'],
     ['StepToTopoDS_Builder', 'StepToTopoDS_PointVertexMap']),
    ('TopoDSToStep', ['Message', 'StepBasic', 'StepGeom', 'Interface',
                      'StepRepr', 'TopLoc', 'Transfer', 'StepData'], []),
    ('STEPControl', ['Message', 'TopLoc', 'StepBasic',
                     'Transfer', 'Geom2d', 'Geom', 'Interface', 'MoniTool'], []),
    ('STEPSelections', ['Message', 'StepBasic', 'TopoDS', 'StepGeom',
                        'TopTools', 'TopLoc', 'Geom', 'Geom2d',
                        'StepData', 'Transfer', 'MoniTool', 'TopoDS'], [],
     {'STEPSelections_Counter': ['POP', 'POP2']}),
    ### TKSTEP209
    ('RWStepElement', ['Message', 'StepShape', 'StepBasic', 'StepGeom', 'StepRepr',
                       'StepElement', 'MoniTool', 'TopoDS'], []),
    ('RWStepFEA', ['Message', 'StepShape', 'StepBasic', 'StepGeom', 'StepRepr',
                   'StepElement', 'MoniTool', 'TopoDS'], [],),
    ('StepElement', ['Message', 'Interface', 'StepBasic', 'StepShape',
                     'StepGeom', 'MoniTool', 'TopoDS'], []),
    ('StepFEA', ['Message', 'Interface', 'StepData', 'StepShape',
                 'MoniTool', 'TopoDS'], [],
     {'StepFEA_SymmetricTensor43d': ['SetFeaIsotropicSymmetricTensor43d']}),
    ### TKSTEPAttr
    ('RWStepDimTol', ['Message', 'StepShape', 'StepBasic', 'StepGeom', 'StepRepr',
                      'StepElement', 'MoniTool', 'TopoDS'], []),
    ('RWStepVisual', ['Message', 'StepShape', 'StepBasic', 'StepGeom', 'StepRepr',
                      'StepElement', 'MoniTool', 'TopoDS'], []),
    ('StepDimTol', ['Message', 'Interface', 'StepGeom', 'StepData',
                    'StepBasic', 'MoniTool', 'TopoDS'], []),
    ('StepVisual', ['Message', 'Interface', 'MoniTool', 'TopoDS'], []),
    ###
    ('StepAP209', ['Message', 'StepBasic', 'StepGeom',
                   'Geom2d', 'StepVisual', 'IFSelect', 'StepAP203', 'Geom',
                   'TopoDS', 'Interface', 'Transfer', 'TopTools',
                   'Quantity', 'TopLoc', 'StepRepr', 'StepData', 'MoniTool'], []),
    # TKIGES
    ('IGESData', ['MoniTool', 'TopoDS'], [],
     {'IGESData_IGESWriter': ['Send'],
      'IGESData_ParamReader': ['ReadEntity']}),
    ('IGESControl', ['Message', 'TopLoc', 'TopTools', 'IGESData',
                     'Geom', 'Geom2d', 'Interface', 'MoniTool', 'TColGeom',
                     'ShapeExtend'], []),
    ('IGESToBRep', ['TColGeom', 'TopTools', 'MoniTool'], [],
     {'IGESToBRep_TopoSurface': ['TransferPlaneSurface']}),
    ('Interface', ['TopoDS'], []),
    ('IFSelect',
     ['TopoDS'],
     [],
     {'IFSelect_EditForm': ['NbTouched'],
      'IFSelect_IntParam': ['StaticName'],
      'IFSelect_ContextModif': ['Search'],
      'IFSelect_WorkSession': ['theerrhand']}),
    ('XSControl', ['Message', 'TopLoc', 'Transfer', 'MoniTool'], []),
    ('Transfer', ['MoniTool', 'TopoDS'], ['Transfer_ProcessForFinder']),
    ('TransferBRep', ['TopLoc', 'MoniTool'], [],
     {'TransferBRep': ['BRepCheck']}), # Fixes undefined ref
    ('MoniTool', [], []),
    ### TKVRML
    ('Vrml', [], []),
    ('VrmlAPI', ['Message', 'Geom', 'GeomAdaptor', 'TShort',
                 'Geom2d', 'Geom2dAdaptor', 'TopLoc', 'HLRAlgo',
                 'BRepAdaptor', 'Adaptor3d', 'Adaptor2d', 'TopTools', 'Poly',
                 'Aspect', 'CDF', 'TDF', 'PCDM'], []),
    ('VrmlConverter', ['Message', 'Geom', 'GeomAdaptor', 'TShort',
                       'Geom2d', 'Geom2dAdaptor', 'TopLoc', 'HLRAlgo',
                       'BRepAdaptor', 'Adaptor3d', 'Adaptor2d', 'TopTools', 'Poly'], []),
    ('VrmlData',
     ['TopLoc', 'Message', 'CDF', 'TDF', 'PCDM'],
     ['VrmlData_InBuffer', 'VrmlData_ArrayVec3d', 'VrmlData_Texture',
      'VrmlData_TextureTransform', 'VrmlData_Faceted'],
     {'VrmlData_IndexedFaceSet': ['GetNormal']}), # Fixes undefined ref
    ('RWGltf', ['CDF', 'PCDM', 'TDF', 'TDocStd', 'Graphic3d', 'Geom',
                'TShort', 'Aspect'], ['RWGltf_GltfSharedIStream']),
    ('RWObj', ['CDF', 'PCDM', 'TDF', 'TDocStd', 'Graphic3d', 'Geom',
               'TShort', 'Aspect', 'Bnd', 'Quantity', 'Message', 'Media'],
     ['RWObj_MtlReader']),
    ###
    ### OCAF
    ###
    ### TKTObj
    ('TObj', ['PCDM', 'CDM', 'CDF', 'Resource'], []),
    ### TKLCAF
    ('TDF', ['TDataStd'], ['TDF_LabelNode']),
    ('TDataStd', [], []),
    ('TFunction', [], []),
    ('TDocStd', [], []),
    ('AppStdL', ['Resource', 'CDF', 'PCDM', 'LDOM', 'TDF', 'CDM', 'Message'], []),
    # 'TKStd': ['ShapePersistent', 'StdDrivers', 'StdObject', 'StdPersistent', 'StdStorage'],
    #('ShapePersistent', [], []),
    #('StdDrivers', [], []),
    #('StdObject', ['CDF', 'TDF', 'TDocStd', 'PCDM', 'TopoDS'], []),
    #('StdPersistent', [], []),
    #('StdStorage', [], []),
    # 'TKStdL': ['StdLDrivers', 'StdLPersistent', 'StdObjMgt'],
    #('StdLDrivers', [], []),
    #('StdLPersistent', ['PCDM', 'CDF', 'TDF', 'TDocStd'], ['*']),
    #('StdObjMgt', [], []),
    ### TKBin
    ('BinDrivers', ['Resource', 'PCDM', 'LDOM', 'TDF', 'CDF'], []),
    ('BinMDataXtd', ['Resource', 'TDF'], []),
    ('BinMNaming', ['Resource', 'Geom', 'TopoDS', 'Geom2d', 'Message',
                    'TopLoc', 'TDF'], []),
    ### TKBinLd
    ('BinLDrivers', ['Resource', 'TDF', 'CDF'], []),
    ('BinMDF', ['Resource', 'TDF'], []),
    ('BinMDataStd', ['Resource', 'TDF'], [],
     {'BinMDataStd' : ['SetAttributeID']}),
    ('BinMDocStd', ['Resource', 'TDF'], []),
    ('BinMFunction', ['Resource', 'TDF'], []),
    ('BinObjMgt', [], []),
    ### TKBinTObj
    ('BinTObjDrivers', ['Resource', 'PCDM', 'LDOM', 'CDF', 'TDF'], []),
    ### TKBinXCAF'
    ('BinXCAFDrivers', ['Resource', 'PCDM', 'LDOM', 'TDF', 'CDF'], []),
    ('BinMXCAFDoc', ['Resource', 'Geom', 'TopoDS', 'Geom2d', 'Message',
                     'XCAFView', 'TDF'], []),
    ### TKXml
    ('XmlDrivers', ['Resource', 'PCDM', 'TDF', 'CDF'], []),
    ('XmlMDataXtd', ['Resource'], []),
    ('XmlMNaming', ['Message', 'Resource', 'TopLoc'], []),
    ('XmlMPrsStd', ['Resource'], []),
    ### TKXmlL
    ('XmlLDrivers', ['Resource', 'TDF', 'CDF'], []),
    ('XmlMDF', ['Resource'], []),
    ('XmlMDataStd', ['Resource'], []),
    ('XmlMDocStd', ['Resource'], []),
    ('XmlMFunction', ['Resource'], []),
    ('XmlObjMgt', [], []),
    ### TKXmlTObj
    ('XmlTObjDrivers', ['Resource', 'PCDM', 'CDF'], []),
    ### TKXmlXCAF
    ('XmlXCAFDrivers', ['Resource', 'PCDM', 'TDF', 'CDF'], []),
    ('XmlMXCAFDoc', ['Message', 'Resource', 'TopoDS', 'XCAFDimTolObjects'], []),
    ### TKCDF
    ('CDF', ['Resource', 'Message'], []),
    ('CDM', [], []),
    ('LDOM', [], ['*']),
    ('PCDM', ['Resource'], ['PCDM_DOMHeaderParser', 'PCDM_Document']),
    ('UTL', [], []),
    ### TKXCAF
    ('XCAFApp', ['CDF', 'CDM', 'PCDM', 'LDOM', 'TDF', 'Resource', 'Message'], []),
    ('XCAFDoc', ['Resource', 'Message', 'CDF', 'CDM', 'PCDM', 'TDF'],
      ['XCAFDoc_GeomTolerance']),
    ('XCAFPrs', ['TopTools', 'Message', 'TShort', 'Poly', 'Aspect',
                 'V3d', 'Select3D', 'Geom', 'HLRAlgo', 'Bnd',
                 'SelectBasics', 'Prs3d', 'Media',
                 'TColQuantity', 'TDF', 'TDataStd', 'TNaming',
                 'TDataXtd', 'Graphic3d', 'SelectMgr', 'TopoDS', 'PrsMgr',
                 'CDF', 'CDM', 'PCDM', 'StdSelect'], []),
    ('XCAFDimTolObjects', ['Message', 'CDF', 'CDM', 'PCDM', 'LDOM', 'TDF',
                           'Resource', 'TopLoc'], []),
    ('XCAFView', [], []),
    ('XCAFNoteObjects', ['Message'], []),
    ### TKCAF
    ('TDataXtd', ['TopTools', 'TCollection', 'Message', 'TopLoc', 'TShort'], []),
    ('TNaming', ['TCollection', 'Message'], []),
    ('TPrsStd', ['TDF', 'gp', 'HLRAlgo', 'TopTools', 'TCollection', 'Geom',
                 'TDataStd', 'Aspect', 'TNaming', 'Select3D',
                 'TColQuantity', 'Message', 'Poly', 'Prs3d', 'Bnd',
                 'TopLoc', 'TShort', 'SelectBasics', 'TopoDS', 'SelectMgr',
                 'PrsMgr', 'V3d', 'Graphic3d', 'StdSelect', 'Media'], []),
    ('AppStd', ['Resource', 'CDF', 'PCDM', 'TDF', 'CDM', 'Message'], []),
    ### TKXDESTEP
    ('STEPCAFControl', ['Interface', 'TopLoc', 'TopTools', 'CDF', 'PCDM',
                        'Message', 'Quantity', 'StepGeom', 'CDM',
                        'StepAP203', 'Resource', 'StepVisual', 'StepData',
                        'Geom', 'Geom2d', 'IFSelect', 'Transfer', 'Resource',
                        'TopLoc', 'XCAFView', 'XSControl', 'StepRepr',
                        'TDataStd', 'MoniTool'], []),
    ### TKXDEIGES
    ('IGESCAFControl', ['Geom2d', 'IFSelect', 'Interface', 'IGESData', 'Geom',
                        'Transfer', 'PCDM', 'TopTools', 'CDF', 'Message',
                        'CDM', 'TopoDS', 'Resource', 'TopLoc', 'XSControl',
                        'ShapeExtend', 'TColGeom', 'MoniTool', 'IGESToBRep'], []),

    ### TOOLKIT_VTK
    ('IVtk', [], []),
    # ('IVtkDraw', [], [])
    ('IVtkOCC', [], []),
    ('IVtkVTK', [], []),
    ('IVtkTools', [], []),
    ]
